### ISSUE TITLE
Resource name and Operation name only available as fixed values

### ISSUE THREAD

**Issue by paulverkooijen** [bramkn/ExactOnline#1]
Several settings are available as fixed or expression
![image](https://user-images.githubusercontent.com/23397054/204308034-1e6ef49e-73d9-467d-b681-57fd1256ceec.png)

Only Resource name and Operation name only available as fixed values

![image](https://user-images.githubusercontent.com/23397054/204307888-bd2976ae-e28c-44ce-af98-ac73e6978073.png)

**Comment by bramkn** [comment]
Seems to have been fixed by me 3 months ago. version 0.1.8 should have it included.

**Comment by bramkn** [comment]
Fixed in the latest version, something went wrong with the publish of 0.1.8
0.2.0 has the correct changes implemented.
